site_name: Sonification Suite
site_description: Documentation for the Sonification Suite
site_url: !ENV READTHEDOCS_CANONICAL_URL

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - User Guide: user-guide/user-guide.md
    - 'Step 1: Data': user-guide/data.md
    - 'Step 2: Refine': user-guide/refine.md
    - 'Step 3: Style': user-guide/style.md
    - 'Step 4: Sonify': user-guide/sonify.md

  - Developer Guide:
    - Developer Guide: developer-guide/developer-guide.md
    - Installation: developer-guide/installation.md
    - Architecture: developer-guide/architecture.md
    - API Reference: developer-guide/api-reference.md

  - About:
    - About: about/about.md
    - Background: about/background.md
    - Release Notes: about/release-notes.md
    - License: about/license.md
    - Credits: about/credits.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material

  # icon:
  #   admonition:
  #     info: octicons/info-16
  #     tip: octicons/squirrel-16
  #     warning: octicons/alert-16

  palette:

    # Automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference