# This schema defines the expected format and valid values when creating a Style File.

# As a .yml file, the Style File should generally follow all the syntax conventions of the YAML language,
# which can be found here: https://yaml.org/spec/1.2.2/#chapter-2-language-overview

# 


# The name can be anything you like, but it must be enclosed in either single or double quote marks.
name: "My Style"


description: "Likewise, the description can be anything you like."

sound:

parameters:
  cutoff:
  pitch:
  azimuth:
