name: "default"

description: >-
  Default style for sonifying light curves. It combines the default
  STRAUSS synth sound with a cutoff filter, and chooses a random chord to play.

sound: "default_synth"

parameters:
  cutoff: [0.25, 0.85]

chord_mode: "on"

chord: "random"






