name: "default"

description: >-
  Default style for sonifying light curves. It combines the default
  STRAUSS synth sound with a cutoff filter, and chooses a random chord to play.

sound: "synth"

parameters:
  cutoff:
    min: 0.25
    max: 0.85


chord_mode: "on"

chord: "random"






